#!/bin/bash

# SafeWatch AI - Vercel Deployment Guide
# This script will guide you through deploying to Vercel

echo "======================================================="
echo "  SafeWatch AI Landing Page - Vercel Deployment"
echo "======================================================="
echo ""

echo "📋 Pre-Deployment Checklist:"
echo ""
echo "✅ Vercel CLI installed (version: $(vercel --version 2>/dev/null | head -1))"
echo "✅ Landing page files ready"
echo "✅ GitHub repository pushed"
echo ""

echo "🚀 DEPLOYMENT OPTIONS:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Option 1: Deploy via Vercel Dashboard (RECOMMENDED)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "This is the easiest method - no CLI authentication needed!"
echo ""
echo "Steps:"
echo "1. Visit: https://vercel.com/new"
echo "2. Click 'Import Git Repository'"
echo "3. Connect your GitHub account (if not already)"
echo "4. Select: Peter07odia/video-search-and-summarization"
echo "5. Configure:"
echo "   - Framework Preset: Other"
echo "   - Root Directory: landing-page"
echo "   - Build Command: (leave empty)"
echo "   - Output Directory: (leave empty)"
echo ""
echo "6. Add Environment Variables:"
echo "   Key: SENDGRID_API_KEY"
echo "   Value: [Your SendGrid API Key]"
echo ""
echo "   Key: FROM_EMAIL"
echo "   Value: hello@yourdomain.com"
echo ""
echo "   Key: ADMIN_EMAIL"
echo "   Value: admin@yourdomain.com"
echo ""
echo "7. Click 'Deploy'"
echo "8. Wait ~2 minutes for deployment"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Option 2: Deploy via Vercel CLI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Steps:"
echo "1. Login to Vercel:"
echo "   $ vercel login"
echo ""
echo "2. Deploy:"
echo "   $ cd landing-page"
echo "   $ vercel"
echo ""
echo "3. Set environment variables:"
echo "   $ vercel env add SENDGRID_API_KEY"
echo "   $ vercel env add FROM_EMAIL"
echo "   $ vercel env add ADMIN_EMAIL"
echo ""
echo "4. Deploy to production:"
echo "   $ vercel --prod"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "📧 SENDGRID SETUP (Required for emails):"
echo ""
echo "1. Create account: https://sendgrid.com"
echo "2. Get API Key:"
echo "   - Go to: Settings → API Keys"
echo "   - Create new key with 'Mail Send' permission"
echo "   - Copy the key (you won't see it again!)"
echo ""
echo "3. Verify sender email:"
echo "   - Go to: Settings → Sender Authentication"
echo "   - Click 'Verify a Single Sender'"
echo "   - Verify the email you'll use as FROM_EMAIL"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

read -p "Press Enter to open Vercel dashboard in your browser..."

# Try to open browser
if command -v xdg-open > /dev/null; then
    xdg-open "https://vercel.com/new" &
elif command -v open > /dev/null; then
    open "https://vercel.com/new" &
else
    echo "Please manually visit: https://vercel.com/new"
fi

echo ""
echo "✨ Your landing page is ready to deploy!"
echo "📁 Repository: Peter07odia/video-search-and-summarization"
echo "📂 Root Directory: landing-page"
echo ""
echo "After deployment, your site will be live at:"
echo "🌐 https://your-project.vercel.app"
echo ""
